const fs = require('fs');
const L = [];
function w(s='') { L.push(s); }

w('#![deny(clippy::all)]');
w('');
w('use anyhow::Result;');
w('use darkiron_transport::DarkIronTransport;');
w('use notify::{recommended_watcher, RecursiveMode, Watcher, Event, EventKind};');
w('use std::path::PathBuf;');
w('use std::sync::mpsc;');
w('use tracing::{info, warn, debug, error};');
w('use uuid::Uuid;');
w('');
w('/// Generate a colored cube mesh as JSON');
w('fn build_cube_scene(session_id: &str) -> serde_json::Value {');
w('    let s: f64 = 0.5;');
w('    let faces: Vec<([f64;3], [f64;3], [[f64;3];4])> = vec![');
w('        // (normal, color, [4 verts])');
w('        ([0.0,0.0,1.0],  [1.0,0.2,0.2], [[-s,-s,s],[s,-s,s],[s,s,s],[-s,s,s]]),      // front red');
w('        ([0.0,0.0,-1.0], [0.2,1.0,1.0], [[s,-s,-s],[-s,-s,-s],[-s,s,-s],[s,s,-s]]),   // back cyan');
w('        ([1.0,0.0,0.0],  [0.2,1.0,0.2], [[s,-s,s],[s,-s,-s],[s,s,-s],[s,s,s]]),        // right green');
w('        ([-1.0,0.0,0.0], [1.0,0.2,1.0], [[-s,-s,-s],[-s,-s,s],[-s,s,s],[-s,s,-s]]),   // left magenta');
w('        ([0.0,1.0,0.0],  [1.0,1.0,0.2], [[-s,s,s],[s,s,s],[s,s,-s],[-s,s,-s]]),        // top yellow');
w('        ([0.0,-1.0,0.0], [0.2,0.2,1.0], [[-s,-s,-s],[s,-s,-s],[s,-s,s],[-s,-s,s]]),    // bottom blue');
w('    ];');
w('');
w('    let mut vertices: Vec<f64> = Vec::new();');
w('    let mut indices: Vec<u32> = Vec::new();');
w('    let mut vi: u32 = 0;');
w('');
w('    for (normal, color, verts) in &faces {');
w('        for v in verts {');
w('            vertices.extend_from_slice(v);');
w('            vertices.extend_from_slice(normal);');
w('            vertices.extend_from_slice(color);');
w('        }');
w('        indices.extend_from_slice(&[vi, vi+1, vi+2, vi, vi+2, vi+3]);');
w('        vi += 4;');
w('    }');
w('');
w('    serde_json::json!({');
w('        "type": "SceneLoaded",');
w('        "session_id": session_id,');
w('        "meshes": [{');
w('            "name": "default_cube",');
w('            "vertices": vertices,');
w('            "indices": indices,');
w('        }]');
w('    })');
w('}');
w('');
w('/// Load a scene from a JSON file');
w('fn load_scene_file(path: &std::path::Path, session_id: &str) -> Result<serde_json::Value> {');
w('    let content = std::fs::read_to_string(path)?;');
w('    let mut scene: serde_json::Value = serde_json::from_str(&content)?;');
w('    // Inject session ID');
w('    if let Some(obj) = scene.as_object_mut() {');
w('        obj.insert("session_id".to_string(), serde_json::json!(session_id));');
w('        if !obj.contains_key("type") {');
w('            obj.insert("type".to_string(), serde_json::json!("SceneLoaded"));');
w('        }');
w('    }');
w('    Ok(scene)');
w('}');
w('');
w('#[tokio::main]');
w('async fn main() -> Result<()> {');
w('    tracing_subscriber::fmt()');
w('        .with_env_filter(');
w('            tracing_subscriber::EnvFilter::try_from_default_env()');
w('                .unwrap_or_else(|_| "info,darkiron=debug".into()),');
w('        )');
w('        .init();');
w('');
w('    info!("╔══════════════════════════════════════╗");');
w('    info!("║  DarkIron Engine Runtime v0.1.0       ║");');
w('    info!("╚══════════════════════════════════════╝");');
w('');
w('    // Connect to NATS');
w('    let nats_url = std::env::var("NATS_URL").unwrap_or_else(|_| "nats://localhost:4222".into());');
w('    info!(url = %nats_url, "Connecting to NATS...");');
w('    let transport = DarkIronTransport::connect(&nats_url).await?;');
w('    info!("Connected to NATS");');
w('');
w('    // Generate session');
w('    let session_id = Uuid::new_v4().to_string();');
w('    info!(session = %session_id, "Session started");');
w('');
w('    // Publish session announcement so editors know which session to subscribe to');
w('    let announce = serde_json::json!({ "session_id": &session_id, "type": "SessionAnnounce" });');
w('    transport.publish("system.session.announce", &serde_json::to_vec(&announce)?).await?;');
w('');
w('    // Small delay to let editors subscribe before we publish scene');
w('    info!("Waiting 1s for editor connections...");');
w('    tokio::time::sleep(std::time::Duration::from_secs(1)).await;');
w('');
w('    // Check for scene files in assets directory, otherwise publish default cube');
w('    let assets_dir = PathBuf::from(std::env::var("DARKIRON_ASSETS").unwrap_or_else(|_| "assets".into()));');
w('    if !assets_dir.exists() {');
w('        std::fs::create_dir_all(&assets_dir)?;');
w('        info!(path = %assets_dir.display(), "Created assets directory");');
w('    }');
w('');
w('    // Look for .json scene files');
w('    let mut scene_loaded = false;');
w('    if let Ok(entries) = std::fs::read_dir(&assets_dir) {');
w('        for entry in entries.flatten() {');
w('            let path = entry.path();');
w('            if path.extension().map_or(false, |e| e == "json") {');
w('                match load_scene_file(&path, &session_id) {');
w('                    Ok(scene) => {');
w('                        let subject = format!("scene.{}.loaded", session_id);');
w('                        transport.publish(&subject, &serde_json::to_vec(&scene)?).await?;');
w('                        info!(file = %path.display(), subject = %subject, "Published scene from file");');
w('                        scene_loaded = true;');
w('                    }');
w('                    Err(e) => warn!(file = %path.display(), error = %e, "Failed to load scene file"),');
w('                }');
w('            }');
w('        }');
w('    }');
w('');
w('    // Publish default cube if no scene files found');
w('    if !scene_loaded {');
w('        let cube = build_cube_scene(&session_id);');
w('        let subject = format!("scene.{}.loaded", session_id);');
w('        transport.publish(&subject, &serde_json::to_vec(&cube)?).await?;');
w('        info!(subject = %subject, "Published default cube scene");');
w('    }');
w('');
w('    // Set up file watcher for hot reload');
w('    let (file_tx, file_rx) = mpsc::channel::<PathBuf>();');
w('    let mut watcher = recommended_watcher(move |res: notify::Result<Event>| {');
w('        if let Ok(event) = res {');
w('            match event.kind {');
w('                EventKind::Create(_) | EventKind::Modify(_) => {');
w('                    for path in event.paths {');
w('                        if path.extension().map_or(false, |e| e == "json") {');
w('                            let _ = file_tx.send(path);');
w('                        }');
w('                    }');
w('                }');
w('                _ => {}');
w('            }');
w('        }');
w('    })?;');
w('    watcher.watch(assets_dir.as_ref(), RecursiveMode::Recursive)?;');
w('    info!(path = %assets_dir.display(), "Watching for asset changes (hot reload)");');
w('');
w('    // Subscribe to editor commands');
w('    let edit_subject = format!("scene.{}.edit.>", session_id);');
w('    let mut subscriber = transport.subscribe(&edit_subject).await?;');
w('    info!(subject = %edit_subject, "Listening for editor commands...");');
w('');
w('    info!("═══ Runtime ready ═══");');
w('');
w('    // Main loop');
w('    loop {');
w('        tokio::select! {');
w('            Some(msg) = subscriber.next() => {');
w('                info!(');
w('                    subject = %msg.subject,');
w('                    bytes = msg.payload.len(),');
w('                    "Received editor command"');
w('                );');
w('            }');
w('            _ = tokio::signal::ctrl_c() => {');
w('                info!("Shutting down...");');
w('                break;');
w('            }');
w('        }');
w('');
w('        // Check for file changes (non-blocking)');
w('        while let Ok(changed_path) = file_rx.try_recv() {');
w('            info!(file = %changed_path.display(), "Asset changed, reloading...");');
w('            // Small debounce — editors often write multiple times');
w('            tokio::time::sleep(std::time::Duration::from_millis(100)).await;');
w('            match load_scene_file(&changed_path, &session_id) {');
w('                Ok(scene) => {');
w('                    let subject = format!("scene.{}.loaded", session_id);');
w('                    if let Err(e) = transport.publish(&subject, &serde_json::to_vec(&scene).unwrap_or_default()).await {');
w('                        error!(error = %e, "Failed to publish reloaded scene");');
w('                    } else {');
w('                        info!(file = %changed_path.display(), "Hot reload published");');
w('                    }');
w('                }');
w('                Err(e) => warn!(file = %changed_path.display(), error = %e, "Failed to reload scene"),');
w('            }');
w('        }');
w('    }');
w('');
w('    Ok(())');
w('}');

fs.writeFileSync('D:/DarkIron/darkiron/crates/darkiron-runtime/src/main.rs', L.join('\n'));
console.log('Lines:', L.length);
console.log('Has file watcher:', L.join('\n').includes('recommended_watcher'));
console.log('Has cube builder:', L.join('\n').includes('build_cube_scene'));
console.log('Has hot reload:', L.join('\n').includes('Hot reload published'));

